###
GET http://localhost:3002/hoteles?ingreso=19sep2025&salida=22sep2025
###
GET http://localhost:3002/hoteles/5
Content-Type: application/json

{
  "habitaciones": [4, 3]
}
###
GET http://localhost:3002/hoteles/10
###
POST http://localhost:3002/hoteles/nuevo
Content-Type: application/json

{
    "nombre": "Hotel Austral Ushuaia",
    "direccion": "9 de Julio 250",
    "estrellas": 3,
    "ciudad": "Ushuaia"
  }
###
DELETE http://localhost:3002/hoteles/11
###
PATCH http://localhost:3002/hoteles/5
Content-Type: application/json

{
  "estrellas": 3
}
### registro
POST http://localhost:3002/cuenta/registro
Content-Type: application/json

{
  "nombre": "nuevo",
  "email": "nuevo@mail.com",
  "password": "password"
}
### ingreso
POST http://localhost:3002/cuenta/ingreso
Content-Type: application/json

{
  "nombre": "nuevo",
  "password": "password"
}
### autenticacion
GET http://localhost:3002/hoteles 
Authorization: Bearer []
Content-Type: application/json

{
  "id": 6
}
