###
GET http://localhost:3002/hoteles 
###
GET http://localhost:3002/hoteles/5
###
GET http://localhost:3002/hoteles/10
###
POST http://localhost:3002/hoteles/nuevo
Content-Type: application/json

{
    "nombre": "Hotel Austral Ushuaia",
    "direccion": "9 de Julio 250",
    "estrellas": 3,
    "ciudad": "Ushuaia"
  }
###
DELETE http://localhost:3002/hoteles/11
###
PATCH http://localhost:3002/hoteles/5
Content-Type: application/json

{
  "estrellas": 3
}
### registro
POST http://localhost:3002/cuenta/registro
Content-Type: application/json

{
  "nombre": "nuevo",
  "email": "nuevo@mail.com",
  "password": "password"
}
### ingreso
POST http://localhost:3002/cuenta/ingreso
Content-Type: application/json

{
  "nombre": "nuevo",
  "password": "password"
}
### autenticacion
GET http://localhost:3002/hoteles 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2wiOiJ1c3VhcmlvIiwiaWF0IjoxNzU4MjA3OTIxLCJleHAiOjE3NTgyMTE1MjF9.tnOQ2a4xsn6jT_dA0tjPaq8EuVUO2oJCmlPOt2JnZDM
Content-Type: application/json

{
  "id": 6
}